INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '94', {_ID}),
('customer_email', 'auto', 'user@@oc.local', {_ID}),
('ip', 'auto', '::1', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'https://oc.local/', {_ID}),
('store_ssl', 'auto', 'https://oc.local/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@oc.local', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_theme', 'auto', 'default', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('date_now', 'auto', '01/03/2019', {_ID}),
('datetime_now', 'auto', 'Friday 01st March 2019', {_ID}),
('login_url', 'auto', 'https://oc.local/index.php?route=account/login', {_ID}),
('cart_url', 'auto', 'https://oc.local/index.php?route=checkout/cart', {_ID}),
('contact_url', 'auto', 'https://oc.local/index.php?route=information/contact', {_ID}),
('home_url', 'auto', 'https://oc.local/index.php?route=common/home', {_ID}),
('privacy_url', 'auto', 'https://oc.local/index.php?route=information/information&information_id=3', {_ID}),
('wrapper_tpl', 'auto', '_main.twig', {_ID}),
('account_login_text', 'auto', 'https://oc.local/index.php?route=account/login', {_ID}),
('customer_store_id', 'auto', '0', {_ID}),
('customer_language_id', 'auto', '0', {_ID}),
('customer_firstname', 'auto', 'John', {_ID}),
('customer_lastname', 'auto', 'Doe', {_ID}),
('customer_telephone', 'auto', '0123456789', {_ID}),
('customer_salt', 'auto', 'cvyE8zfw5', {_ID}),
('customer_newsletter', 'auto', '1', {_ID}),
('customer_address_id', 'auto', '0', {_ID}),
('customer_custom_field', 'auto', '{\"1\":\"123\"}', {_ID}),
('customer_status', 'auto', '1', {_ID}),
('customer_safe', 'auto', '0', {_ID}),
('customer_date_added', 'auto', '2019-03-01 13:51:16', {_ID}),
('custom_field.1', 'auto', '123', {_ID}),
('firstname', 'auto', 'John', {_ID}),
('lastname', 'auto', 'Doe', {_ID}),
('email', 'auto', 'user@@oc.local', {_ID}),
('telephone', 'auto', '0123456789', {_ID}),
('notify', 'auto', '1', {_ID}),
('newsletter', 'auto', 'Yes', {_ID}),
('preference_notification', 'auto', '1', {_ID}),
('preference_showcase', 'auto', '1', {_ID}),
('status', 'auto', '1', {_ID}),
('safe', 'auto', '0', {_ID}),
('commission', 'auto', '5', {_ID}),
('payment', 'auto', 'cheque', {_ID}),
('affiliate', 'auto', '0', {_ID}),
('account_login', 'auto', 'https://oc.local/index.php?route=account/login', {_ID}),
('customer_group', 'auto', 'Default', {_ID}),
('customer_text', 'auto', 'Login into Store', {_ID}),
('unsubscribe_url', 'auto', 'https://oc.local/index.php?route=extension/module/emailtemplate_newsletter/unsubscribe&token=IXC2v0X6tWR9rAIiMU7Wm1PunSHAyP6S', {_ID}),
('preference_url', 'auto', 'https://oc.local/index.php?route=extension/module/emailtemplate_newsletter&token=IXC2v0X6tWR9rAIiMU7Wm1PunSHAyP6S', {_ID}),
('mail.to', 'auto', 'user@@oc.local', {_ID}),
('mail.from', 'auto', 'store@oc.local', {_ID}),
('mail.sender', 'auto', 'Your Store', {_ID}),
('mail.subject', 'auto', 'Your Store account has been created', {_ID}),
('mail.text', 'auto', 'Welcome and thank you for registering at Your Store!\n\nYour account has now been created and you can log in by using your email address and password at the following URL:\n\nhttps://oc.local/index.php?route=account/login\n\nUpon logging in, you will be able to generate tracking codes, track commission payments and edit your account information.\n\nThanks,\n[Your Store](https://oc.local/)', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_enabled', 'language', 'Enabled', {_ID}),
('text_disabled', 'language', 'Disabled', {_ID}),
('text_select_all', 'language', 'Select All', {_ID}),
('text_unselect_all', 'language', 'Unselect All', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_close', 'language', 'Close', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('text_confirm', 'language', 'Are you sure?', {_ID}),
('text_home', 'language', 'Home', {_ID}),
('button_add', 'language', 'Add New', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_save', 'language', 'Save', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_cancel_recurring', 'language', 'Cancel Recurring Payments', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_clear', 'language', 'Clear', {_ID}),
('button_close', 'language', 'Close', {_ID}),
('button_enable', 'language', 'Enable', {_ID}),
('button_disable', 'language', 'Disable', {_ID}),
('button_filter', 'language', 'Filter', {_ID}),
('button_send', 'language', 'Send', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_copy', 'language', 'Copy', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_refresh', 'language', 'Refresh', {_ID}),
('button_export', 'language', 'Export', {_ID}),
('button_import', 'language', 'Import', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_rebuild', 'language', 'Rebuild', {_ID}),
('button_upload', 'language', 'Upload', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_invoice_print', 'language', 'Print Invoice', {_ID}),
('button_shipping_print', 'language', 'Print Shipping List', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_attribute_add', 'language', 'Add Attribute', {_ID}),
('button_banner_add', 'language', 'Add Banner', {_ID}),
('button_custom_field_value_add', 'language', 'Add Custom Field', {_ID}),
('button_product_add', 'language', 'Add Product', {_ID}),
('button_filter_add', 'language', 'Add Filter', {_ID}),
('button_option_add', 'language', 'Add Option', {_ID}),
('button_option_value_add', 'language', 'Add Option Value', {_ID}),
('button_recurring_add', 'language', 'Add Recurring', {_ID}),
('button_discount_add', 'language', 'Add Discount', {_ID}),
('button_special_add', 'language', 'Add Special', {_ID}),
('button_image_add', 'language', 'Add Image', {_ID}),
('button_geo_zone_add', 'language', 'Add Geo Zone', {_ID}),
('button_history_add', 'language', 'Add History', {_ID}),
('button_translation', 'language', 'Load Default Translation', {_ID}),
('button_translation_add', 'language', 'Add Translation', {_ID}),
('button_transaction_add', 'language', 'Add Transaction', {_ID}),
('button_route_add', 'language', 'Add Route', {_ID}),
('button_rule_add', 'language', 'Add Rule', {_ID}),
('button_module_add', 'language', 'Add Module', {_ID}),
('button_link_add', 'language', 'Add Link', {_ID}),
('button_approve', 'language', 'Approve', {_ID}),
('button_deny', 'language', 'Deny', {_ID}),
('button_reset', 'language', 'Reset', {_ID}),
('button_generate', 'language', 'Generate', {_ID}),
('button_voucher_add', 'language', 'Add Voucher', {_ID}),
('button_reward_add', 'language', 'Add Reward Points', {_ID}),
('button_reward_remove', 'language', 'Remove Reward Points', {_ID}),
('button_commission_add', 'language', 'Add Commission', {_ID}),
('button_commission_remove', 'language', 'Remove Commission', {_ID}),
('button_credit_add', 'language', 'Add Credit', {_ID}),
('button_credit_remove', 'language', 'Remove Credit', {_ID}),
('button_ip_add', 'language', 'Add IP', {_ID}),
('button_parent', 'language', 'Parent', {_ID}),
('button_folder', 'language', 'New Folder', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_install', 'language', 'Install', {_ID}),
('button_uninstall', 'language', 'Uninstall', {_ID}),
('button_link', 'language', 'Link', {_ID}),
('button_currency', 'language', 'Refresh Currency Values', {_ID}),
('button_apply', 'language', 'Apply', {_ID}),
('button_category_add', 'language', 'Add Category', {_ID}),
('button_order', 'language', 'View Order', {_ID}),
('button_order_recurring', 'language', 'View Recurring Order', {_ID}),
('button_buy', 'language', 'Buy', {_ID}),
('tab_affiliate', 'language', 'Affiliate', {_ID}),
('tab_address', 'language', 'Address', {_ID}),
('tab_additional', 'language', 'Additional', {_ID}),
('tab_admin', 'language', 'Admin', {_ID}),
('tab_attribute', 'language', 'Attribute', {_ID}),
('tab_customer', 'language', 'Customer Details', {_ID}),
('tab_comment', 'language', 'Comment', {_ID}),
('tab_data', 'language', 'Data', {_ID}),
('tab_description', 'language', 'Description', {_ID}),
('tab_design', 'language', 'Design', {_ID}),
('tab_discount', 'language', 'Discount', {_ID}),
('tab_documentation', 'language', 'Documentation', {_ID}),
('tab_general', 'language', 'General', {_ID}),
('tab_history', 'language', 'History', {_ID}),
('tab_ftp', 'language', 'FTP', {_ID}),
('tab_ip', 'language', 'IP Addresses', {_ID}),
('tab_links', 'language', 'Links', {_ID}),
('tab_log', 'language', 'Log', {_ID}),
('tab_image', 'language', 'Image', {_ID}),
('tab_option', 'language', 'Option', {_ID}),
('tab_server', 'language', 'Server', {_ID}),
('tab_seo', 'language', 'SEO', {_ID}),
('tab_store', 'language', 'Store', {_ID}),
('tab_special', 'language', 'Special', {_ID}),
('tab_session', 'language', 'Session', {_ID}),
('tab_local', 'language', 'Local', {_ID}),
('tab_mail', 'language', 'Mail', {_ID}),
('tab_module', 'language', 'Module', {_ID}),
('tab_payment', 'language', 'Payment Details', {_ID}),
('tab_product', 'language', 'Products', {_ID}),
('tab_reward', 'language', 'Reward Points', {_ID}),
('tab_shipping', 'language', 'Shipping Details', {_ID}),
('tab_total', 'language', 'Totals', {_ID}),
('tab_transaction', 'language', 'Transactions', {_ID}),
('tab_voucher', 'language', 'Vouchers', {_ID}),
('tab_sale', 'language', 'Sales', {_ID}),
('tab_marketing', 'language', 'Marketing', {_ID}),
('tab_online', 'language', 'People Online', {_ID}),
('tab_activity', 'language', 'Recent Activity', {_ID}),
('tab_recurring', 'language', 'Recurring', {_ID}),
('tab_action', 'language', 'Action', {_ID}),
('tab_google', 'language', 'Google', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('datepicker', 'language', 'en-gb', {_ID}),
('button_cart_checkout', 'language', 'Finish Order', {_ID}),
('text_emailtemplate_cart_title', 'language', '{{ customer_firstname }} you\'ve left something in your cart', {_ID}),
('text_emailtemplate_footer', 'language', '&lt;div&gt;\r\n&lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;width:100%&quot;&gt;\r\n	&lt;tbody&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;10&quot; style=&quot;font-size:1px; line-height:10px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td style=&quot;color:#666666; font-size:13px&quot;&gt;If you have any questions please do not hesitate to contact us via our &lt;a href=&quot;{{ contact_url }}&quot;&gt;website contact us form&lt;/a&gt;, email: &lt;a href=&quot;mailto:{{ store_email }}&quot;&gt;{{ store_email }}&lt;/a&gt; or phone us on &lt;a href=&quot;tel:{{ store_telephone }}&quot; style=&quot;    white-space: nowrap;&quot;&gt;{{ store_telephone }}&lt;/a&gt and we will be happy to help.&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;5&quot; style=&quot;font-size:1px; line-height:5px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td&gt;&lt;strong&gt;{{ store_name }}&lt;/strong&gt;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n	&lt;/tbody&gt;\r\n&lt;/table&gt;\r\n&lt;/div&gt;\r\n', {_ID}),
('text_example', 'language', '<div>Preview text for: {{ store_name }}.\n<br />\n</div>\n<table width=\'100%\' cellpadding=\'0\' cellspacing=\'0\'>\n    <tr>\n        <td>\n            <table class=\'link\' cellspacing=\'0\' cellpadding=\'0\' width=\'auto\' align=\'left\' style=\'width:auto;\'>\n                <tbody>\n                    <tr>\n                        <td><a href=\'{{ store_url }}\' target=\'_blank\'><b>{{ store_url }}</b></a>\n                        </td>\n                    </tr>\n                </tbody>\n            </table>\n        </td>\n    </tr>\n</table>', {_ID}),
('text_price', 'language', 'Price', {_ID}),
('text_product', 'language', 'Product', {_ID}),
('text_quantity', 'language', 'Quantity', {_ID}),
('text_rating', 'language', 'Rating', {_ID}),
('text_total', 'language', 'Total', {_ID}),
('text_view_browser', 'language', 'If you\'re having difficulty viewing this email <a href=\"%s\" target=\"_blank\">open in a browser</a>.', {_ID}),
('button_select', 'language', 'Select', {_ID}),
('entry_template', 'language', 'Email Template:', {_ID}),
('text_account_login', 'language', 'You can log in by visiting the following URL:', {_ID}),
('text_address', 'language', 'Address', {_ID}),
('text_approval', 'language', 'Your account must be approved before you can login. Once approved you can log in by using your email address and password at the following URL:', {_ID}),
('text_approved', 'language', 'Your account has now been approved and you can log in by using your email address and password at the following URL:', {_ID}),
('text_created', 'language', 'Your account has now been created and you can log in by using your email address and password at the following URL:', {_ID}),
('text_comment', 'language', 'Comment', {_ID}),
('text_company', 'language', 'Company', {_ID}),
('text_create_status', 'language', 'Status', {_ID}),
('text_create_subject', 'language', '{{ store_name }} account has been created', {_ID}),
('text_create_heading', 'language', 'Welcome to {{ store_name }}', {_ID}),
('text_create_services', 'language', 'Upon logging in, you will be able to generate tracking codes, track commission payments and edit your account information.', {_ID}),
('text_create_thanks', 'language', 'Thanks,', {_ID}),
('text_customer_group', 'language', 'Customer group', {_ID}),
('text_customer_subject', 'language', '{{ store_name }} - New Message', {_ID}),
('text_date_added', 'language', 'Date', {_ID}),
('text_email', 'language', 'Email', {_ID}),
('text_fax', 'language', 'Fax', {_ID}),
('text_name', 'language', 'Name', {_ID}),
('text_newsletter', 'language', 'Newsletter', {_ID}),
('text_password', 'language', 'Password', {_ID}),
('text_reward_heading', 'language', 'Reward Points', {_ID}),
('text_telephone', 'language', 'Telephone', {_ID}),
('text_transaction_heading', 'language', 'Account Credit', {_ID}),
('text_welcome', 'language', 'Welcome and thank you for registering at %s!', {_ID}),
('text_deny_heading', 'language', 'Your Account has been denied at {{ store_name }}', {_ID}),
('text_deny_subject', 'language', '{{ store_name }} Account has been denied!', {_ID}),
('text_deny_welcome', 'language', 'Unfortunately your request has been denied. For more information you can contact the store owner here:', {_ID}),
('text_deny_thanks', 'language', 'Thanks,', {_ID}),
('text_approve_subject', 'language', '{{ store_name }} Account has been activated!', {_ID}),
('text_approve_heading', 'language', 'Welcome and thank you for registering at {{ store_name }}!', {_ID}),
('text_approve_login', 'language', 'Your account has now been approved and you can now log in by using your email address and password by visiting our website or at the following URL:', {_ID}),
('text_approve_services', 'language', 'Upon logging in, you will be able to access other services including reviewing past orders, printing invoices and editing your account information.', {_ID}),
('text_approve_thanks', 'language', 'Thanks,', {_ID}),
('text_transaction_subject', 'language', '{{ store_name }} - Account Credit', {_ID}),
('text_transaction_received', 'language', 'You have received {{ customer_transaction_received }} credit!', {_ID}),
('text_transaction_total', 'language', 'Your total amount of credit is now {{ customer_transaction_total }}.\n\nYour account credit will be automatically deducted from your next purchase.', {_ID}),
('text_reward_subject', 'language', '{{ store_name }} - Reward Points', {_ID}),
('text_reward_received', 'language', 'You have received {{ customer_reward_points }} Reward Points!', {_ID}),
('text_reward_total', 'language', 'Your total number of reward points is now {{ customer_reward_total }}.', {_ID}),
('warning_template_content', 'language', 'Are you sure you want to change the template? This will clear all of the text inside the editor', {_ID});