INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '93', {_ID}),
('customer_email', 'auto', 'user@@oc.local', {_ID}),
('ip', 'auto', '::1', {_ID}),
('store_title', 'auto', '0', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'https://oc.local/', {_ID}),
('store_ssl', 'auto', 'https://oc.local/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@oc.local', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_theme', 'auto', 'default', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('store_theme_dir', 'auto', 'default/extension/module/emailtemplate/', {_ID}),
('date_now', 'auto', '01/03/2019', {_ID}),
('datetime_now', 'auto', 'Friday 01st March 2019', {_ID}),
('login_url', 'auto', 'https://oc.local/index.php?route=account/login', {_ID}),
('cart_url', 'auto', 'https://oc.local/index.php?route=checkout/cart', {_ID}),
('contact_url', 'auto', 'https://oc.local/index.php?route=information/contact', {_ID}),
('home_url', 'auto', 'https://oc.local/index.php?route=common/home', {_ID}),
('privacy_url', 'auto', 'https://oc.local/index.php?route=information/information&amp;information_id=3', {_ID}),
('wrapper_tpl', 'auto', '_main.twig', {_ID}),
('affiliate_customer_group_id', 'auto', '1', {_ID}),
('affiliate_custom_field', 'auto_serialize', 'YToxOntzOjc6ImFjY291bnQiO2E6MTp7aToxO3M6MzoiMTIzIjt9fQ==', {_ID}),
('affiliate_firstname', 'auto', 'John', {_ID}),
('affiliate_lastname', 'auto', 'Doe', {_ID}),
('affiliate_email', 'auto', 'user@@oc.local', {_ID}),
('affiliate_telephone', 'auto', '+44123456789', {_ID}),
('affiliate_company', 'auto', 'Opencart-templates', {_ID}),
('affiliate_payment', 'auto', 'cheque', {_ID}),
('affiliate_cheque', 'auto', 'Opencart-templates', {_ID}),
('affiliate_password', 'auto', 'W3b2W0rks', {_ID}),
('affiliate_confirm', 'auto', 'W3b2W0rks', {_ID}),
('affiliate_agree', 'auto', '1', {_ID}),
('customer_store_id', 'auto', '0', {_ID}),
('customer_language_id', 'auto', '1', {_ID}),
('customer_firstname', 'auto', 'John', {_ID}),
('customer_lastname', 'auto', 'Doe', {_ID}),
('customer_telephone', 'auto', '+44123456789', {_ID}),
('customer_salt', 'auto', 'kesdWqEtj', {_ID}),
('customer_newsletter', 'auto', '0', {_ID}),
('customer_address_id', 'auto', '0', {_ID}),
('customer_custom_field', 'auto', '{\"1\":\"123\"}', {_ID}),
('customer_ip', 'auto', '::1', {_ID}),
('customer_status', 'auto', '0', {_ID}),
('customer_safe', 'auto', '0', {_ID}),
('customer_date_added', 'auto', '2019-03-01 13:51:16', {_ID}),
('text_firstname', 'auto', 'First Name:', {_ID}),
('text_lastname', 'auto', 'Last Name:', {_ID}),
('firstname', 'auto', 'John', {_ID}),
('lastname', 'auto', 'Doe', {_ID}),
('email', 'auto', 'user@@oc.local', {_ID}),
('telephone', 'auto', '+44123456789', {_ID}),
('company', 'auto', 'Opencart-templates', {_ID}),
('customer_group', 'auto', 'Default', {_ID}),
('affiliate_login', 'auto', 'https://oc.local/index.php?route=affiliate/login', {_ID}),
('affiliate_login_text', 'auto', 'https://oc.local/index.php?route=affiliate/login', {_ID}),
('subject', 'auto', 'New Affiliate requires approval', {_ID}),
('affiliate_link', 'auto', 'https://oc.local/admin/index.php?route=customer/customer_approval&filter_type=affiliate&filter_email=user@@oc.local', {_ID}),
('status', 'auto', 'Request Approval', {_ID}),
('affiliate_link_text', 'auto', 'https://oc.local/admin/index.php?route=customer/customer_approval&filter_type=affiliate&filter_email=user@@oc.local', {_ID}),
('unsubscribe_url', 'auto', 'https://oc.local/index.php?route=extension/module/emailtemplate_newsletter/unsubscribe&token=qFwtpA94OZzEq8ItEnt8BOuziKK3zSfR', {_ID}),
('preference_url', 'auto', 'https://oc.local/index.php?route=extension/module/emailtemplate_newsletter&token=qFwtpA94OZzEq8ItEnt8BOuziKK3zSfR', {_ID}),
('mail.to', 'auto', 'store@oc.local', {_ID}),
('mail.from', 'auto', 'user@@oc.local', {_ID}),
('mail.sender', 'auto', 'John Doe', {_ID}),
('mail.subject', 'auto', 'New Affiliate requires approval', {_ID}),
('mail.text', 'auto', 'A new affiliate has signed up:\n\nCompany: Default\nWeb Site: \nFirst Name: John\nLast Name: Doe\nCustomer Group: Default\nE-Mail: user@@oc.local\nTelephone: +44123456789\n', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('datepicker', 'language', 'en-gb', {_ID}),
('button_cart_checkout', 'language', 'Finish Order', {_ID}),
('text_emailtemplate_cart_title', 'language', '{{ customer_firstname }} you\'ve left something in your cart', {_ID}),
('text_emailtemplate_footer', 'language', '&lt;div&gt;\r\n&lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;width:100%&quot;&gt;\r\n	&lt;tbody&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;10&quot; style=&quot;font-size:1px; line-height:10px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td style=&quot;color:#666666; font-size:13px&quot;&gt;If you have any questions please do not hesitate to contact us via our &lt;a href=&quot;{{ contact_url }}&quot;&gt;website contact us form&lt;/a&gt;, email: &lt;a href=&quot;mailto:{{ store_email }}&quot;&gt;{{ store_email }}&lt;/a&gt; or phone us on &lt;a href=&quot;tel:{{ store_telephone }}&quot; style=&quot;    white-space: nowrap;&quot;&gt;{{ store_telephone }}&lt;/a&gt and we will be happy to help.&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;5&quot; style=&quot;font-size:1px; line-height:5px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td&gt;&lt;strong&gt;{{ store_name }}&lt;/strong&gt;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n	&lt;/tbody&gt;\r\n&lt;/table&gt;\r\n&lt;/div&gt;\r\n', {_ID}),
('text_price', 'language', 'Price', {_ID}),
('text_product', 'language', 'Product', {_ID}),
('text_quantity', 'language', 'Quantity', {_ID}),
('text_rating', 'language', 'Rating', {_ID}),
('text_total', 'language', 'Total', {_ID}),
('text_view_browser', 'language', 'If you\'re having difficulty viewing this email <a href=\"%s\" target=\"_blank\">open in a browser</a>.', {_ID}),
('text_affiliate_subject', 'language', '{{ store_name }} - Affiliate Program', {_ID}),
('text_affiliate_welcome', 'language', 'Thank you for joining the {{ store_name }} Affiliate Program!', {_ID}),
('text_affiliate_approve', 'language', 'Customer requires approval!', {_ID}),
('text_affiliate_link', 'language', 'Edit Affiliate:', {_ID}),
('text_admin_approve', 'language', 'Request Approval', {_ID}),
('text_customer_group', 'language', 'Customer Group:', {_ID}),
('text_company', 'language', 'Company:', {_ID}),
('text_email', 'language', 'Email:', {_ID}),
('text_name', 'language', 'Name:', {_ID}),
('text_telephone', 'language', 'Telephone:', {_ID}),
('text_subject', 'language', '%s - Affiliate Program', {_ID}),
('text_welcome', 'language', 'Thank you for joining the %s Affiliate Program!', {_ID}),
('text_login', 'language', 'Your account has now been created and you can log in by using your e-mail address and password by visiting our website or at the following URL:', {_ID}),
('text_approval', 'language', 'Your account must be approved before you can login. Once approved you can log in by using your e-mail address and password by visiting our website or at the following URL:', {_ID}),
('text_services', 'language', 'Upon logging in, you will be able to generate tracking codes, track commission payments and edit your account information.', {_ID}),
('text_thanks', 'language', 'Thanks,', {_ID}),
('text_new_affiliate', 'language', 'New Affiliate', {_ID}),
('text_signup', 'language', 'A new affiliate has signed up:', {_ID}),
('text_status', 'language', 'Status:', {_ID}),
('text_store', 'language', 'Store:', {_ID}),
('text_website', 'language', 'Web Site:', {_ID}),
('text_order_id', 'language', 'Order ID:', {_ID}),
('text_subject_admin', 'language', 'New Affiliate', {_ID}),
('text_approve_subject_admin', 'language', 'New Affiliate requires approval', {_ID}),
('text_enabled', 'language', 'Enabled', {_ID}),
('text_disabled', 'language', 'Disabled', {_ID}),
('text_transaction_subject', 'language', '{{ store_name }} - Affiliate Commission', {_ID}),
('text_transaction_received', 'language', 'You have received {{ customer_transaction_received }} commission!', {_ID}),
('text_transaction_total', 'language', 'Your total amount of commission is now {{ customer_transaction_total }}.', {_ID});