INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '92', {_ID}),
('customer_email', 'auto', 'user@@oc.local', {_ID}),
('ip', 'auto', '::1', {_ID}),
('store_title', 'auto', '0', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'https://oc.local/', {_ID}),
('store_ssl', 'auto', 'https://oc.local/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@oc.local', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_theme', 'auto', 'default', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('store_theme_dir', 'auto', 'default/extension/module/emailtemplate/', {_ID}),
('date_now', 'auto', '01/03/2019', {_ID}),
('datetime_now', 'auto', 'Friday 01st March 2019', {_ID}),
('login_url', 'auto', 'https://oc.local/index.php?route=account/login', {_ID}),
('cart_url', 'auto', 'https://oc.local/index.php?route=checkout/cart', {_ID}),
('contact_url', 'auto', 'https://oc.local/index.php?route=information/contact', {_ID}),
('home_url', 'auto', 'https://oc.local/index.php?route=common/home', {_ID}),
('privacy_url', 'auto', 'https://oc.local/index.php?route=information/information&amp;information_id=3', {_ID}),
('wrapper_tpl', 'auto', '_main.twig', {_ID}),
('order_id', 'auto', '1', {_ID}),
('order_invoice_no', 'auto', 'INV-2018-0030', {_ID}),
('order_invoice_prefix', 'auto', 'INV-2018-00', {_ID}),
('order_store_id', 'auto', '0', {_ID}),
('order_store_name', 'auto', 'Your Store', {_ID}),
('order_store_url', 'auto', 'https://oc.local/', {_ID}),
('order_customer_id', 'auto', '92', {_ID}),
('order_affiliate_id', 'auto', '0', {_ID}),
('order_customer_group_id', 'auto', '1', {_ID}),
('order_weight', 'auto', '0.00000000', {_ID}),
('order_firstname', 'auto', 'John', {_ID}),
('order_lastname', 'auto', 'Doe', {_ID}),
('order_email', 'auto', 'user@@oc.local', {_ID}),
('order_telephone', 'auto', '+44123456789', {_ID}),
('order_custom_field.1', 'auto', '123', {_ID}),
('order_payment_firstname', 'auto', 'John', {_ID}),
('order_payment_lastname', 'auto', 'Doe', {_ID}),
('order_payment_company', 'auto', 'Opencart-templates', {_ID}),
('order_payment_address_1', 'auto', '1 Long Lane', {_ID}),
('order_payment_postcode', 'auto', 'L12 1EP', {_ID}),
('order_payment_city', 'auto', 'London', {_ID}),
('order_payment_zone_id', 'auto', '3592', {_ID}),
('order_payment_zone', 'auto', 'South Ayrshire', {_ID}),
('order_payment_zone_code', 'auto', 'ARYS', {_ID}),
('order_payment_country_id', 'auto', '222', {_ID}),
('order_payment_country', 'auto', 'United Kingdom', {_ID}),
('order_payment_iso_code_2', 'auto', 'GB', {_ID}),
('order_payment_iso_code_3', 'auto', 'GBR', {_ID}),
('order_payment_custom_field.2', 'auto', 'Leave with number 12 ', {_ID}),
('order_payment_method', 'auto', 'Bank Transfer', {_ID}),
('order_payment_code', 'auto', 'bank_transfer', {_ID}),
('order_shipping_firstname', 'auto', 'John', {_ID}),
('order_shipping_lastname', 'auto', 'Doe', {_ID}),
('order_shipping_company', 'auto', 'Opencart-templates', {_ID}),
('order_shipping_address_1', 'auto', '1 Long Lane', {_ID}),
('order_shipping_postcode', 'auto', 'L12 1EP', {_ID}),
('order_shipping_city', 'auto', 'London', {_ID}),
('order_shipping_zone_id', 'auto', '3592', {_ID}),
('order_shipping_zone', 'auto', 'South Ayrshire', {_ID}),
('order_shipping_zone_code', 'auto', 'ARYS', {_ID}),
('order_shipping_country_id', 'auto', '222', {_ID}),
('order_shipping_country', 'auto', 'United Kingdom', {_ID}),
('order_shipping_iso_code_2', 'auto', 'GB', {_ID}),
('order_shipping_iso_code_3', 'auto', 'GBR', {_ID}),
('order_shipping_custom_field.2', 'auto', 'Leave with number 12 ', {_ID}),
('order_shipping_method', 'auto', 'Flat Shipping Rate', {_ID}),
('order_shipping_code', 'auto', 'flat.flat', {_ID}),
('order_comment', 'auto', 'Test comments\nWith line breaks.', {_ID}),
('order_total', 'auto', '$838.00', {_ID}),
('order_status_id', 'auto', '5', {_ID}),
('order_status', 'auto', 'Complete', {_ID}),
('order_commission', 'auto', '0.0000', {_ID}),
('order_language_id', 'auto', '1', {_ID}),
('order_language_code', 'auto', 'en-gb', {_ID}),
('order_currency_id', 'auto', '2', {_ID}),
('order_currency_code', 'auto', 'USD', {_ID}),
('order_currency_value', 'auto', '1.00000000', {_ID}),
('order_ip', 'auto', '::1', {_ID}),
('order_user_agent', 'auto', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36', {_ID}),
('order_accept_language', 'auto', 'en-GB,en-US;q=0.9,en;q=0.8', {_ID}),
('order_date_added', 'auto', '2019-03-01 13:51:16', {_ID}),
('order_date_modified', 'auto', '2019-03-01 13:00:43', {_ID}),
('order_date', 'auto', '01/03/2019', {_ID}),
('order_payment_address', 'auto', 'John Doe<br />Opencart-templates<br />1 Long Lane<br />London L12 1EP<br />South Ayrshire<br />United Kingdom', {_ID}),
('order_shipping_address', 'auto', 'John Doe<br />Opencart-templates<br />1 Long Lane<br />London L12 1EP<br />South Ayrshire<br />United Kingdom', {_ID}),
('return_id', 'auto', '8', {_ID}),
('firstname', 'auto', 'John', {_ID}),
('lastname', 'auto', 'Doe', {_ID}),
('email', 'auto', 'user@@oc.local', {_ID}),
('telephone', 'auto', '+44123456789', {_ID}),
('product', 'auto', 'Canon EOS 5D', {_ID}),
('model', 'auto', 'Product 3', {_ID}),
('quantity', 'auto', '1', {_ID}),
('opened', 'auto', 'No', {_ID}),
('reason', 'auto', 'Received Wrong Item', {_ID}),
('status', 'auto', 'Awaiting Products', {_ID}),
('comment', 'auto', 'Wrong color', {_ID}),
('date_ordered', 'auto', '2019-03-01', {_ID}),
('date_added', 'auto', '2019-03-01 13:51:16', {_ID}),
('date_modified', 'auto', '2019-03-01 13:51:16', {_ID}),
('customer_store_id', 'auto', '0', {_ID}),
('customer_language_id', 'auto', '1', {_ID}),
('customer_firstname', 'auto', 'John', {_ID}),
('customer_lastname', 'auto', 'Doe', {_ID}),
('customer_telephone', 'auto', '+44123456789', {_ID}),
('customer_salt', 'auto', 'dmRGly4wC', {_ID}),
('customer_newsletter', 'auto', '1', {_ID}),
('customer_address_id', 'auto', '16', {_ID}),
('customer_custom_field', 'auto', '{\"1\":\"123\"}', {_ID}),
('customer_ip', 'auto', '::1', {_ID}),
('customer_status', 'auto', '1', {_ID}),
('customer_safe', 'auto', '0', {_ID}),
('customer_date_added', 'auto', '2019-03-01 13:51:16', {_ID}),
('customer_last_visit_date', 'auto', '2019-03-01 12:57:29', {_ID}),
('customer_last_visit_url', 'auto', 'https://oc.local/opencart_advanced/opencart_advanced_3021/upload/admin/index.php?route=common/login', {_ID}),
('customer_accept_language', 'auto', 'en-GB,en-US;q=0.9,en;q=0.8', {_ID}),
('return_date', 'auto', '01/03/2019', {_ID}),
('return_link', 'auto', 'https://oc.local/admin/index.php?route=sale%2Freturn%2Finfo&return_id=8', {_ID}),
('return_link_text', 'auto', 'https://oc.local/admin/index.php?route=sale%2Freturn%2Finfo&return_id=8', {_ID}),
('unsubscribe_url', 'auto', 'https://oc.local/index.php?route=extension/module/emailtemplate_newsletter/unsubscribe&token=OJYwfcIEVIkfmrFS0xxPufob7u4DJ9Yy', {_ID}),
('preference_url', 'auto', 'https://oc.local/index.php?route=extension/module/emailtemplate_newsletter&token=OJYwfcIEVIkfmrFS0xxPufob7u4DJ9Yy', {_ID}),
('mail.to', 'auto', 'user@@oc.local', {_ID}),
('mail.from', 'auto', 'store@oc.local', {_ID}),
('mail.sender', 'auto', 'Your Store', {_ID}),
('mail.subject', 'auto', 'Your Store Return Details', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('datepicker', 'language', 'en-gb', {_ID}),
('button_cart_checkout', 'language', 'Finish Order', {_ID}),
('text_emailtemplate_cart_title', 'language', '{{ customer_firstname }} you\'ve left something in your cart', {_ID}),
('text_emailtemplate_footer', 'language', '&lt;div&gt;\r\n&lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;width:100%&quot;&gt;\r\n	&lt;tbody&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;10&quot; style=&quot;font-size:1px; line-height:10px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td style=&quot;color:#666666; font-size:13px&quot;&gt;If you have any questions please do not hesitate to contact us via our &lt;a href=&quot;{{ contact_url }}&quot;&gt;website contact us form&lt;/a&gt;, email: &lt;a href=&quot;mailto:{{ store_email }}&quot;&gt;{{ store_email }}&lt;/a&gt; or phone us on &lt;a href=&quot;tel:{{ store_telephone }}&quot; style=&quot;    white-space: nowrap;&quot;&gt;{{ store_telephone }}&lt;/a&gt and we will be happy to help.&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;5&quot; style=&quot;font-size:1px; line-height:5px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td&gt;&lt;strong&gt;{{ store_name }}&lt;/strong&gt;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n	&lt;/tbody&gt;\r\n&lt;/table&gt;\r\n&lt;/div&gt;\r\n', {_ID}),
('text_price', 'language', 'Price', {_ID}),
('text_product', 'language', 'Product', {_ID}),
('text_quantity', 'language', 'Quantity', {_ID}),
('text_rating', 'language', 'Rating', {_ID}),
('text_total', 'language', 'Total', {_ID}),
('text_view_browser', 'language', 'If you\'re having difficulty viewing this email <a href=\"%s\" target=\"_blank\">open in a browser</a>.', {_ID}),
('text_action', 'language', 'Login into admin for further details', {_ID}),
('text_comment', 'language', 'Return Comments:', {_ID}),
('text_email', 'language', 'E-Mail:', {_ID}),
('text_name', 'language', 'Name:', {_ID}),
('text_greeting', 'language', 'A new product return has been placed at: {{ store_name }}', {_ID}),
('text_date', 'language', 'Date:', {_ID}),
('text_model', 'language', 'Model:', {_ID}),
('text_opened', 'language', 'Opened:', {_ID}),
('text_order', 'language', 'Order Information', {_ID}),
('text_order_id', 'language', 'Order ID:', {_ID}),
('text_order_date', 'language', 'Order Date:', {_ID}),
('text_order_total', 'language', 'Order Total:', {_ID}),
('text_reason', 'language', 'Reason', {_ID}),
('text_return', 'language', 'Return Information', {_ID}),
('text_return_date', 'language', 'Return Details', {_ID}),
('text_return_detail', 'language', 'Return Details', {_ID}),
('text_return_id', 'language', 'Return ID:', {_ID}),
('text_subject', 'language', '{{ store_name }} Return Details', {_ID}),
('text_telephone', 'language', 'Telephone', {_ID}),
('text_customer_subject', 'language', 'We have received the return for Order: {{ order_id }}', {_ID}),
('text_customer_greeting', 'language', 'Thank you for your recent order at {{ store_name }}', {_ID}),
('text_customer_welcome', 'language', 'Your return request has been sent to the relevant department for processing. You will be notified again via e-mail when the status of your request changes.', {_ID}),
('text_thanks', 'language', 'Thanks,', {_ID});