INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '92', {_ID}),
('customer_email', 'auto', 'user@@oc.local', {_ID}),
('ip', 'auto', '::1', {_ID}),
('store_title', 'auto', '0', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'https://oc.local/', {_ID}),
('store_ssl', 'auto', 'https://oc.local/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@oc.local', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_theme', 'auto', 'default', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('store_theme_dir', 'auto', 'default/extension/module/emailtemplate/', {_ID}),
('date_now', 'auto', '01/03/2019', {_ID}),
('datetime_now', 'auto', 'Friday 01st March 2019', {_ID}),
('login_url', 'auto', 'https://oc.local/index.php?route=account/login', {_ID}),
('cart_url', 'auto', 'https://oc.local/index.php?route=checkout/cart', {_ID}),
('contact_url', 'auto', 'https://oc.local/index.php?route=information/contact', {_ID}),
('home_url', 'auto', 'https://oc.local/index.php?route=common/home', {_ID}),
('privacy_url', 'auto', 'https://oc.local/index.php?route=information/information&amp;information_id=3', {_ID}),
('wrapper_tpl', 'auto', '_main.twig', {_ID}),
('review_name', 'auto', 'John Doe', {_ID}),
('review_text', 'auto', 'Awesome product with amazing customer service!', {_ID}),
('review_rating', 'auto', '5', {_ID}),
('product_id', 'auto', '28', {_ID}),
('product_name', 'auto', 'HTC Touch HD', {_ID}),
('product_description', 'auto', '&lt;p&gt;\r\n	HTC Touch - in High Definition. Watch music videos and streaming content in awe-inspiring high definition clarity for a mobile experience you never thought possible. Seductively sleek, the HTC Touch HD provides the next generation of mobile functionality, all at a simple touch. Fully integrated with Windows Mobile Professional 6.1, ultrafast 3.5G, GPS, 5MP camera, plus lots more - all delivered on a breathtakingly crisp 3.8&amp;quot; WVGA touchscreen - you can take control of your mobile world with the HTC Touch HD.&lt;/p&gt;\r\n&lt;p&gt;\r\n	&lt;strong&gt;Features&lt;/strong&gt;&lt;/p&gt;\r\n&lt;ul&gt;\r\n	&lt;li&gt;\r\n		Processor Qualcomm&amp;reg; MSM 7201A&amp;trade; 528 MHz&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Windows Mobile&amp;reg; 6.1 Professional Operating System&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Memory: 512 MB ROM, 288 MB RAM&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Dimensions: 115 mm x 62.8 mm x 12 mm / 146.4 grams&lt;/li&gt;\r\n	&lt;li&gt;\r\n		3.8-inch TFT-LCD flat touch-sensitive screen with 480 x 800 WVGA resolution&lt;/li&gt;\r\n	&lt;li&gt;\r\n		HSDPA/WCDMA: Europe/Asia: 900/2100 MHz; Up to 2 Mbps up-link and 7.2 Mbps down-link speeds&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Quad-band GSM/GPRS/EDGE: Europe/Asia: 850/900/1800/1900 MHz (Band frequency, HSUPA availability, and data speed are operator dependent.)&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Device Control via HTC TouchFLO&amp;trade; 3D &amp;amp; Touch-sensitive front panel buttons&lt;/li&gt;\r\n	&lt;li&gt;\r\n		GPS and A-GPS ready&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Bluetooth&amp;reg; 2.0 with Enhanced Data Rate and A2DP for wireless stereo headsets&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Wi-Fi&amp;reg;: IEEE 802.11 b/g&lt;/li&gt;\r\n	&lt;li&gt;\r\n		HTC ExtUSB&amp;trade; (11-pin mini-USB 2.0)&lt;/li&gt;\r\n	&lt;li&gt;\r\n		5 megapixel color camera with auto focus&lt;/li&gt;\r\n	&lt;li&gt;\r\n		VGA CMOS color camera&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Built-in 3.5 mm audio jack, microphone, speaker, and FM radio&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Ring tone formats: AAC, AAC+, eAAC+, AMR-NB, AMR-WB, QCP, MP3, WMA, WAV&lt;/li&gt;\r\n	&lt;li&gt;\r\n		40 polyphonic and standard MIDI format 0 and 1 (SMF)/SP MIDI&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Rechargeable Lithium-ion or Lithium-ion polymer 1350 mAh battery&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Expansion Slot: microSD&amp;trade; memory card (SD 2.0 compatible)&lt;/li&gt;\r\n	&lt;li&gt;\r\n		AC Adapter Voltage range/frequency: 100 ~ 240V AC, 50/60 Hz DC output: 5V and 1A&lt;/li&gt;\r\n	&lt;li&gt;\r\n		Special Features: FM Radio, G-Sensor&lt;/li&gt;\r\n&lt;/ul&gt;\r\n', {_ID}),
('product_meta_title', 'auto', '	 HTC Touch HD', {_ID}),
('product_model', 'auto', 'Product 1', {_ID}),
('product_quantity', 'auto', '930', {_ID}),
('product_stock_status', 'auto', 'In Stock', {_ID}),
('product_image', 'auto', 'catalog/demo/htc_touch_hd_1.jpg', {_ID}),
('product_manufacturer_id', 'auto', '5', {_ID}),
('product_manufacturer', 'auto', 'HTC', {_ID}),
('product_price', 'auto', '100.0000', {_ID}),
('product_reward', 'auto', '400', {_ID}),
('product_points', 'auto', '200', {_ID}),
('product_tax_class_id', 'auto', '9', {_ID}),
('product_date_available', 'auto', '2019-03-01 13:51:16', {_ID}),
('product_weight', 'auto', '146.40000000', {_ID}),
('product_weight_class_id', 'auto', '2', {_ID}),
('product_length', 'auto', '0.00000000', {_ID}),
('product_width', 'auto', '0.00000000', {_ID}),
('product_height', 'auto', '0.00000000', {_ID}),
('product_length_class_id', 'auto', '1', {_ID}),
('product_subtract', 'auto', '1', {_ID}),
('product_rating', 'auto', '0', {_ID}),
('product_reviews', 'auto', '0', {_ID}),
('product_minimum', 'auto', '1', {_ID}),
('product_sort_order', 'auto', '0', {_ID}),
('product_status', 'auto', '1', {_ID}),
('product_date_added', 'auto', '2019-03-01 13:51:16', {_ID}),
('product_date_modified', 'auto', '2019-03-01 13:51:16', {_ID}),
('product_viewed', 'auto', '1', {_ID}),
('review_approve', 'auto', 'https://oc.local/admin/index.php?route=catalog/review/edit&review_id=', {_ID}),
('review_approve_text', 'auto', 'https://oc.local/admin/index.php?route=catalog/review/edit&review_id=', {_ID}),
('customer_link', 'auto', 'https://oc.local/admin/index.php?route=customer/customer/edit&filter_name=', {_ID}),
('customer_link_text', 'auto', 'https://oc.local/admin/index.php?route=customer/customer/edit&filter_name=', {_ID}),
('product_link', 'auto', 'https://oc.local/index.php?route=product/product&amp;product_id=28', {_ID}),
('unsubscribe_url', 'auto', 'https://oc.local/index.php?route=extension/module/emailtemplate_newsletter/unsubscribe&token=OJYwfcIEVIkfmrFS0xxPufob7u4DJ9Yy', {_ID}),
('preference_url', 'auto', 'https://oc.local/index.php?route=extension/module/emailtemplate_newsletter&token=OJYwfcIEVIkfmrFS0xxPufob7u4DJ9Yy', {_ID}),
('mail.to', 'auto', 'store@oc.local', {_ID}),
('mail.from', 'auto', 'store@oc.local', {_ID}),
('mail.sender', 'auto', 'John Doe', {_ID}),
('mail.subject', 'auto', 'Your Store - Product Review', {_ID}),
('mail.text', 'auto', 'You have a new product review waiting.\nProduct: HTC Touch HD\nReviewer: John Doe\nRating: 5\nReview Text:\nAwesome product with amazing customer service!\n\n', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('datepicker', 'language', 'en-gb', {_ID}),
('button_cart_checkout', 'language', 'Finish Order', {_ID}),
('text_emailtemplate_cart_title', 'language', '{{ customer_firstname }} you\'ve left something in your cart', {_ID}),
('text_emailtemplate_footer', 'language', '&lt;div&gt;\r\n&lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;width:100%&quot;&gt;\r\n	&lt;tbody&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;10&quot; style=&quot;font-size:1px; line-height:10px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td style=&quot;color:#666666; font-size:13px&quot;&gt;If you have any questions please do not hesitate to contact us via our &lt;a href=&quot;{{ contact_url }}&quot;&gt;website contact us form&lt;/a&gt;, email: &lt;a href=&quot;mailto:{{ store_email }}&quot;&gt;{{ store_email }}&lt;/a&gt; or phone us on &lt;a href=&quot;tel:{{ store_telephone }}&quot; style=&quot;    white-space: nowrap;&quot;&gt;{{ store_telephone }}&lt;/a&gt and we will be happy to help.&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td height=&quot;5&quot; style=&quot;font-size:1px; line-height:5px; mso-margin-top-alt:1px&quot;&gt;&amp;nbsp;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n		&lt;tr&gt;\r\n			&lt;td&gt;&lt;strong&gt;{{ store_name }}&lt;/strong&gt;&lt;/td&gt;\r\n		&lt;/tr&gt;\r\n	&lt;/tbody&gt;\r\n&lt;/table&gt;\r\n&lt;/div&gt;\r\n', {_ID}),
('text_price', 'language', 'Price', {_ID}),
('text_product', 'language', 'Product: %s', {_ID}),
('text_quantity', 'language', 'Quantity', {_ID}),
('text_rating', 'language', 'Rating: %s', {_ID}),
('text_total', 'language', 'Total', {_ID}),
('text_view_browser', 'language', 'If you\'re having difficulty viewing this email <a href=\"%s\" target=\"_blank\">open in a browser</a>.', {_ID}),
('text_subject', 'language', '%s - Product Review', {_ID}),
('text_waiting', 'language', 'You have a new product review waiting.', {_ID}),
('text_reviewer', 'language', 'Reviewer: %s', {_ID}),
('text_review', 'language', 'Review Text:', {_ID}),
('text_review_approve', 'language', 'To approve review click on the link below', {_ID}),
('text_review_heading', 'language', 'New review awaiting approval for: %s', {_ID}),
('text_review_message', 'language', 'Message:', {_ID}),
('text_review_product', 'language', 'Product:', {_ID}),
('text_review_customer', 'language', 'Customer:', {_ID}),
('text_review_rating', 'language', 'Rating:', {_ID}),
('text_review_review', 'language', 'You have received a new review for', {_ID}),
('text_review_reviewer', 'language', 'Reviewer:', {_ID});